<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <base href="/mount/ultralaser_home/Projects/c2_wiki_recovery/out/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="page">
      <h1>
        <img src="wiki.gif" />
        Auto Desk
      </h1>
      <p>
        <a href="http://www.autodesk.com/">http://www.autodesk.com/</a>
      </p>
      <p>
        Founded by <a href="JohnWalker.html">JohnWalker</a> 
      </p>
      <hr/>
      <p>
        <a href="CategoryCompany.html">CategoryCompany</a>
        (defun C:SLOT ( )
      </p>
      <code>
        (setvar "CMDECHO" 0)<br/>
        (setvar "BLIPMODE" 0)<br/>
        (setq oldsnap (getvar "OSMODE"))<br/>
      </code>
      <code>
        (setq diam (getdist "\nSlot Diameter : ")<br/>
        lngth (getdist "\nSlot Length : "))<br/>
      </code>
      <code>
        (while<br/>
      </code>
      <code>
        (setq pt1 (getpoint "\nInsertion point:"))<br/>
        (setvar "OSMODE" 0)<br/>
        (setq pt2 (polar pt1 0.0 (/ (- lngth diam) 2.0))<br/>
        pt3 (polar pt2 (/ pi 2.0) (/ diam 4.0))<br/>
        pt4 (polar pt3 pi (- lngth diam))<br/>
        pt5 (polar pt4 (* pi 1.5) (/ diam 2.0))<br/>
        pt6 (polar pt5 0.0 (- lngth diam)))<br/>
      </code>
      <code>
        (command "PLINE" pt3 "W" (/ diam 2.0) "" pt4<br/>
        "ARC" pt5 "LINE" pt6 "ARC" "CLOSE")<br/>
        (setvar "OSMODE" oldsnap)<br/>
        );while<br/>
        (princ)<br/>
      </code>
    </div>
  </body>
</html>